server:
  port: 9999
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  config:
    import: "configserver:"
  application:
    name: gateway-discovery
#  cloud:
#    config:
#      uri: http://localhost:8888
    gateway:
      metrics:
        enable: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  enpoint:
    gateway:
      enable: true