server:
  port: 9999
spring:
  application:
    name: gateway
  cloud:
    gateway:
      metrics:
        enable: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  enpoint:
    gateway:
      enable: true